version: '3.7'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./database/db:/var/lib/postgresql/data
    restart: on-failure
    container_name: "pg_book_catalog"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${DB_PORT}:${DB_PORT}"

